# Generated by Django 2.0.5 on 2018-05-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_num',
            new_name='goods_num',
        ),
    ]
