# Generated by Django 2.0.5 on 2018-05-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180504_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_desc',
            new_name='goods_desc',
        ),
    ]
