# Generated by Django 2.0.5 on 2018-05-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20180518_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='desc',
            field=models.TextField(blank=True, help_text='品牌描述', null=True, verbose_name='品牌描述'),
        ),
    ]
