# Generated by Django 2.0.5 on 2018-05-16 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180516_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='trade.OrderInfo', verbose_name='所属订单')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ShoppingCart', verbose_name='所属购物车')),
            ],
            options={
                'verbose_name': '购物车订单',
                'verbose_name_plural': '购物车订单',
            },
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='trade.OrderInfo', verbose_name='所属订单'),
        ),
    ]
