# Generated by Django 2.0.5 on 2018-05-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20180516_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='所属订单'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSED', '超时关闭'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_FINISHED', '交易结束'), ('unpaid', '待支付')], default='unpaid', max_length=30, verbose_name='交易状态'),
        ),
    ]
