# Generated by Django 2.0.5 on 2018-05-03 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0002_auto_20180503_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLeaveMessage',
            new_name='UserLeavingMessage',
        ),
    ]
