# Generated by Django 2.0.5 on 2018-05-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20180515_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='district',
            new_name='area',
        ),
    ]
